#====================treemap plot of all crimes in india==================================
library(treemap)
table=read.csv("E:/project/crimes.csv")
rap_crime=table %>% summarise(rap_crime = sum(Rape))
kidnap_crime=table %>% summarise(kidnap_crime = sum(Kidnapping.and.Abduction))
dowry_crime=table %>% summarise(dowry_crime = sum(Dowry.Deaths))
assult_crime=table %>% summarise(assult_crime = sum(Assault.on.women.with.intent.to.outrage.her.modesty))
insult_crime=table %>% summarise(insult_crime = sum(Insult.to.modesty.of.Women))
by_rel_crime=table %>% summarise(by_rel_crime = sum(Cruelty.by.Husband.or.his.Relatives))
imp_crime=table %>% summarise(imp_crime = sum(Importation.of.Girls))
all_crimes=c(rap_crime,kidnap_crime,dowry_crime,assult_crime,insult_crime,by_rel_crime,imp_crime)
tr_crimes=as.numeric(paste(all_crimes))
header=c("Rape","Kidnapping.and.Abduction","Dowry.Deaths","Assault.on.women.with.intent.to.outrage.her.modesty","Insult.to.modesty.of.Women","cruelty.by.Husband.or.his.Relatives","Importation")
my_tree=cbind(header,tr_crimes)
df=data.frame(header,tr_crimes)
str(df)
transform(df,all_crimes=as.numeric(all_crimes))
str(df)
print(df)
treemap(df,index = "header",vSize = "tr_crimes",type = "index",fontface.labels = 6,bg.labels = "transparent",title = "treemap about all crimes",title.legend = "tr_crimes")